ecommerce_homepage:     # name of route
    path:     /hello/{firstName}/{lastName}    # URL path with {variable1}/{variable2}
    defaults: { _controller: EcommerceBundle:Default:index }
# _controller: Name_of_bundle:Name_of_controller:Name_of_method
# _controller: EcommerceBundle:(DefaultController):(IndexAction)